# Generated by Django 5.0.6 on 2024-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_information_animal_is_rare_animal_population_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='')),
                ('last_name', models.CharField(max_length=30, verbose_name='')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Фото сотрудника')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('mammal', 'Млекопитающее'), ('fish', 'Рыба'), ('reptile', 'Рептилия')], default='mammal', max_length=100, verbose_name='Род'),
        ),
    ]
