# Generated by Django 5.0.6 on 2024-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staff_alter_animal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Слово')),
                ('long_text', models.TextField(blank=True, verbose_name='Длинный текст')),
            ],
            options={
                'verbose_name': 'Переворот',
                'verbose_name_plural': 'Переворот',
            },
        ),
    ]
