# Generated by Django 5.0.6 on 2024-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='text_now',
            field=models.TextField(blank=True, verbose_name='Запись'),
        ),
    ]
