# Generated by Django 5.0.6 on 2024-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_times_time_now'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Times',
        ),
    ]
