# Generated by Django 5.0.6 on 2024-05-18 17:41

import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name': datetime.datetime(2024, 5, 18, 22, 41, 54, 308469), 'verbose_name_plural': 'Время'},
        ),
    ]
