# Generated by Django 5.0.6 on 2024-05-18 17:42

import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_times_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name': 'Время', 'verbose_name_plural': datetime.datetime(2024, 5, 18, 22, 42, 18, 708970)},
        ),
    ]
