# Generated by Django 5.0.6 on 2024-05-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_times_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
    ]
