# Generated by Django 5.0.6 on 2024-05-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_times_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Times',
            new_name='Timess',
        ),
    ]
