# Generated by Django 5.0.6 on 2024-05-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_times_timess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timess',
        ),
    ]
