# Generated by Django 5.0.6 on 2024-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_timess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('information', models.TextField(blank=True, verbose_name='Информация')),
                ('vaznoe_time', models.DateField(verbose_name='Важная дата')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
    ]
