# Generated by Django 5.0.6 on 2024-05-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_timess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timess',
        ),
    ]
