# Generated by Django 5.0.6 on 2024-05-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name_plural': '2024-05-19 12:07:43.689468'},
        ),
    ]
