# Generated by Django 5.0.6 on 2024-05-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_times_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Times',
        ),
    ]
