# Generated by Django 5.0.6 on 2024-05-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_animal_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Sot',
        ),
    ]
